spring:
  datasource:
    username: admin
    password: 89710000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://umc-ch3.cbaivxcqjfhs.ap-northeast-2.rds.amazonaws.com:3306/CarrotMarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

  jpa:
    open-in-view: true

    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정